# Generated by Django 3.0.7 on 2020-10-19 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='membro_de', to=settings.AUTH_USER_MODEL),
        ),
    ]
