# Generated by Django 3.0.7 on 2020-06-28 15:20

from django.db import migrations, models
import phonenumber_field.modelfields
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('nome', models.CharField(max_length=300)),
                ('avatar', models.ImageField(null=True, upload_to=usuarios.models.upload_directory_path)),
                ('apresentacao', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
